// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrTzXtONG9SAQS1baRJ4tpLS-IfIhwIwc',
    appId: '1:322150511311:web:7ded65a7f6678aa52d3dba',
    messagingSenderId: '322150511311',
    projectId: 'socially-cb039',
    authDomain: 'socially-cb039.firebaseapp.com',
    storageBucket: 'socially-cb039.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmzl5EGSQ_3MpALSxE2vPfACyg1sNXhH4',
    appId: '1:322150511311:android:fe9031dcb687d4cc2d3dba',
    messagingSenderId: '322150511311',
    projectId: 'socially-cb039',
    storageBucket: 'socially-cb039.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEG30iLGXk9cPSBSsWzqINvZtDd4iOIh4',
    appId: '1:322150511311:ios:2d5a22583b0d1ce22d3dba',
    messagingSenderId: '322150511311',
    projectId: 'socially-cb039',
    storageBucket: 'socially-cb039.firebasestorage.app',
    iosBundleId: 'com.example.socially',
  );
}
